# Generated by Django 4.2.5 on 2023-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_model', '0001_initial'),
        ('car_brand', '0001_initial'),
        ('city', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdvert',
            fields=[
                ('id', models.CharField(default='aca388d7-29d3-4bf6-8a4c-89abd46351c4', editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('liquefied petroleum', 'Liquefied Petroleum'), ('CNG', 'Compressed Natural Gas'), ('ethanol', 'Ethanol'), ('bio-diesel', 'Bio-Diesel')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='car_brand.carbrand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='city.city')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='car_model.carmodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='state.state')),
            ],
            options={
                'db_table': 'car_adverts',
            },
        ),
    ]
