# Generated by Django 4.2.5 on 2024-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_advert", "0003_caradvert_is_cloud_server_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caradvert",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("liquefied petroleum", "Liquefied Petroleum"),
                    ("CNG", "Compressed Natural Gas"),
                    ("ethanol", "Ethanol"),
                    ("bio-diesel", "Bio-Diesel"),
                ],
                max_length=110,
            ),
        ),
        migrations.RunSQL(
            sql= 'CREATE FULLTEXT INDEX car_advert_fulltext_idx ON car_adverts (title, tag, description);',
            reverse_sql='DROP INDEX car_advert_fulltext_idx ON car_adverts;'
        ),
    ]
